
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todolist_with_api_development
  username: root
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
